version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/vite-react-app
      - /usr/src/app/vite-react-app/node_modules
    ports:
      - '3000:3000'
    environment:
      - WATCHPACK_POLLING=true